"""Streamlit AppTest smoke tests for every page.

Each page is loaded via ``AppTest.from_file`` with only the data-loading
functions mocked — the rest of the code (filters, helpers, charts) runs
for real, giving us cheap end-to-end coverage.

Requires: ``tests/data/fixtures/*.csv`` (generated by
``scripts/generate_test_fixtures.py``).
"""
from __future__ import annotations

from collections.abc import Callable
from typing import Any
from unittest.mock import patch

import pytest
from streamlit.testing.v1 import AppTest

# Page modules are not imported directly; AppTest runs them from file.

# ---------------------------------------------------------------------------
# Shared factory
# ---------------------------------------------------------------------------

_PAGE_DIR = "Pages"


def _make_app(
    page_file: str,
    make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    patches: list[str],
) -> AppTest:
    """Build an ``AppTest`` for *page_file* with the given loader patches."""
    txns, bal, cats, accts = make_full_dataset()

    lookup: dict[str, Any] = {
        "src.spreadsheet.load_transactions_data": txns,
        "src.spreadsheet.load_balance_history_data": bal,
        "src.spreadsheet.load_categories_data": cats,
        "src.spreadsheet.load_accounts_data": accts,
    }

    # Stack the patches — each target → the corresponding spreadsheet object
    ctx = [patch(target, return_value=lookup[target]) for target in patches]
    for c in ctx:
        c.start()

    try:
        at = AppTest.from_file(f"{_PAGE_DIR}/{page_file}", default_timeout=30)
        at.run()
    finally:
        for c in ctx:
            c.stop()

    return at


# ---------------------------------------------------------------------------
# Smoke tests — every page boots without error
# ---------------------------------------------------------------------------

@pytest.mark.uses_real_dates
class TestHomeSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "../Home.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestIncomeAndSavingsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "1_Income_and_Savings.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestSpendingByCategorySmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "2_Spending_by_Category.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestYearOverYearSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "3_Year_over_Year.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestDuplicateDetectionSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "4_Duplicate_Detection.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestSubscriptionsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "5_Subscriptions.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestMerchantAnalysisSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "6_Merchant_Analysis.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestBudgetSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "7_Budget.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_categories_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestTopTransactionsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "8_Top_Transactions.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception


@pytest.mark.uses_real_dates
class TestFinancialIndependenceSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: Callable[..., tuple[Any, Any, Any, Any]],
    ) -> None:
        at = _make_app(
            "9_Financial_Independence.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception
