"""Streamlit AppTest smoke tests for every page.

Each page is loaded via ``AppTest.from_file`` with only the data-loading
functions mocked — the rest of the code (filters, helpers, charts) runs
for real, giving us cheap end-to-end coverage.

Requires: ``tests/data/fixtures/*.csv`` (generated by
``scripts/generate_test_fixtures.py``).
"""
from collections.abc import Callable
from unittest.mock import patch

import pytest
from streamlit.testing.v1 import AppTest

from tests.custom_types import FullDatasetFactory

# Page modules are not imported directly; AppTest runs them from file.

# ---------------------------------------------------------------------------
# Shared factory
# ---------------------------------------------------------------------------

_PAGE_DIR = "pages"


def _metric_values(at: AppTest) -> list[tuple[str, str, str]]:
    """Return rendered metric labels, values, and deltas in page order."""
    return [(metric.label, metric.value, metric.delta) for metric in at.metric]


def _select_three_months(at: AppTest) -> None:
    at.selectbox[0].set_value(3)


def _select_top_ten(at: AppTest) -> None:
    at.slider[0].set_value(10)


def _set_five_percent_return(at: AppTest) -> None:
    at.number_input[1].set_value(5.0)


def _exclude_utility_subscription(at: AppTest) -> None:
    at.multiselect[3].set_value(["UTILITY POWER BILL"])


def _make_app(
    page_file: str,
    make_full_dataset: FullDatasetFactory,
    patches: list[str],
    interact: Callable[[AppTest], None] | None = None,
) -> AppTest:
    """Build an ``AppTest`` for *page_file* with the given loader patches."""
    txns, bal, cats, accts = make_full_dataset()

    lookup: dict[str, object] = {
        "src.spreadsheet.load_transactions_data": txns,
        "src.spreadsheet.load_balance_history_data": bal,
        "src.spreadsheet.load_categories_data": cats,
        "src.spreadsheet.load_accounts_data": accts,
    }

    # Stack the patches — each target → the corresponding spreadsheet object
    ctx = [patch(target, return_value=lookup[target]) for target in patches]
    for c in ctx:
        c.start()

    try:
        at = AppTest.from_file(f"{_PAGE_DIR}/{page_file}", default_timeout=30)
        at.run()
        if interact is not None:
            interact(at)
            at.run()
    finally:
        for c in ctx:
            c.stop()

    return at


# ---------------------------------------------------------------------------
# Smoke tests — every page boots without error
# ---------------------------------------------------------------------------

@pytest.mark.uses_real_dates
class TestHomeSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "../Home.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Total Net Worth", "$182,500.00", ""),
            ("Credit Cards", "$1,700.00", ""),
            ("Retirement", "$230,000.00", ""),
            ("Investments", "$146,000.00", ""),
            ("Savings", "$6,200.00", ""),
            ("Liabilities", "$198,000.00", ""),
            ("_SyntheticZeroGroup", "$0.00", ""),
        ]


@pytest.mark.uses_real_dates
class TestIncomeAndSavingsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "1_Income_and_Savings.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Monthly Avg Rate", "44.2%", ""),
            ("Overall Rate", "44.2%", ""),
            ("Monthly Avg Amount", "$2,211", ""),
            ("Overall Amount", "$24,323", ""),
        ]

    def test_three_month_selection_updates_metrics(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "1_Income_and_Savings.py",
            make_full_dataset,
            ["src.spreadsheet.load_transactions_data"],
            _select_three_months,
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Monthly Avg Rate", "19.5%", ""),
            ("Overall Rate", "19.5%", ""),
            ("Monthly Avg Amount", "$977", ""),
            ("Overall Amount", "$2,932", ""),
        ]


@pytest.mark.uses_real_dates
class TestSpendingByCategorySmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "2_Spending_by_Category.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Total Spending", "$12,057.57", ""),
            ("Top Category", "Shopping", "$5,000.00"),
            ("Active Categories", "6", ""),
            ("Median Transaction", "$150.00", ""),
            ("Average Transaction", "$548.07", ""),
            ("75th Percentile", "$400.00", ""),
            ("90th Percentile", "$1600.00", ""),
            ("Total Transactions", "22", ""),
            ("# Transactions", "6", ""),
            ("% of Total $", "0.6%", ""),
            ("# Transactions", "7", ""),
            ("% of Total $", "5.6%", ""),
            ("# Transactions", "9", ""),
            ("% of Total $", "93.7%", ""),
        ]


@pytest.mark.uses_real_dates
class TestYearOverYearSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "3_Year_over_Year.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert [tab.label for tab in at.tabs] == ["By Category", "By Group"]
        assert len(at.dataframe) == 6
        assert at.dataframe[0].value.to_numpy().sum() == pytest.approx(5_275.30)
        assert at.dataframe[2].value.to_numpy().sum() == pytest.approx(5_000.0)
        assert at.dataframe[4].value.to_numpy().sum() == pytest.approx(95.94)


@pytest.mark.uses_real_dates
class TestSubscriptionsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "5_Subscriptions.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert [widget.label for widget in at.multiselect] == [
            "Cadences",
            "Exclude Groups",
            "Exclude Categories",
            "Exclude Transactions",
        ]
        assert at.multiselect[1].value == ["Food", "Shopping"]
        assert _metric_values(at) == [
            ("Detected Subscriptions", "3", ""),
            ("Total Monthly Cost", "$145.98", ""),
            ("Projected Annual Cost", "$1,751.76", ""),
            ("Average Subscription", "$48.66/mo", ""),
        ]

    def test_transaction_exclusion_updates_metrics(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "5_Subscriptions.py",
            make_full_dataset,
            ["src.spreadsheet.load_transactions_data"],
            _exclude_utility_subscription,
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Detected Subscriptions", "2", ""),
            ("Total Monthly Cost", "$25.98", ""),
            ("Projected Annual Cost", "$311.76", ""),
            ("Average Subscription", "$12.99/mo", ""),
        ]


@pytest.mark.uses_real_dates
class TestMerchantAnalysisSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "6_Merchant_Analysis.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Total Merchants", "8", ""),
            ("Total Spent", "$32,884.87", ""),
            ("Top Merchant", "APARTMENT RENT", "$19,200.00"),
            ("Avg Spent/Merchant", "$4,110.61", ""),
        ]


@pytest.mark.uses_real_dates
class TestBudgetSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "7_Budget.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_categories_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Monthly budget", "$5,940.00", ""),
            ("Monthly spent", "$2,645.98", ""),
            ("Monthly remaining", "$3,294.02", ""),
            ("Monthly used", "44.5%", ""),
            ("YTD budget", "$22,710.00", ""),
            ("YTD spent", "$14,713.55", ""),
            ("YTD remaining", "$7,996.45", ""),
            ("YTD used", "64.8%", ""),
        ]


@pytest.mark.uses_real_dates
class TestTopTransactionsSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "8_Top_Transactions.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Total (Top N)", "$28,600.00", ""),
            ("Total Spending", "$33,322.52", ""),
            ("% of Total", "85.8%", ""),
            ("All Expenses", "70", ""),
        ]

    def test_top_ten_selection_updates_metrics(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "8_Top_Transactions.py",
            make_full_dataset,
            ["src.spreadsheet.load_transactions_data"],
            _select_top_ten,
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Total (Top N)", "$17,800.00", ""),
            ("Total Spending", "$33,322.52", ""),
            ("% of Total", "53.4%", ""),
            ("All Expenses", "70", ""),
        ]


@pytest.mark.uses_real_dates
class TestFinancialIndependenceSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "9_Financial_Independence.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Portfolio Value", "$382,200", ""),
            ("Annual Spending", "$33,465", ""),
            ("Supplemental Income", "$0", ""),
            ("Additional Spending", "$0", ""),
            ("Expected Annual Return", "$26,754", ""),
            ("Coverage", "79.9%", "Not yet"),
            ("Runway", "23.7 yrs", ""),
            ("Total Spending", "$33,465", "$-6,711 vs inflow"),
        ]

    def test_return_rate_scenario_updates_fi_metrics(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "9_Financial_Independence.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
            ],
            _set_five_percent_return,
        )
        assert not at.exception
        assert _metric_values(at)[4:] == [
            ("Expected Annual Return", "$26,754", ""),
            ("Coverage", "79.9%", "Not yet"),
            ("Runway", "23.7 yrs", ""),
            ("Total Spending", "$33,465", "$-6,711 vs inflow"),
        ]


@pytest.mark.uses_real_dates
class TestDataHealthSmoke:

    def test_runs_without_exception(
        self, make_full_dataset: FullDatasetFactory,
    ) -> None:
        at = _make_app(
            "10_Data_Health.py",
            make_full_dataset,
            [
                "src.spreadsheet.load_transactions_data",
                "src.spreadsheet.load_balance_history_data",
                "src.spreadsheet.load_categories_data",
            ],
        )
        assert not at.exception
        assert _metric_values(at) == [
            ("Uncategorized", "0", ""),
            ("Sign Issues", "0", ""),
            ("Potential Duplicates", "3", ""),
            ("Unmapped Accounts", "0", ""),
            ("Stale Accounts", "0", ""),
            ("Unbudgeted Categories", "0", ""),
        ]
        assert "Flagged amount: $249.49 | Affected months: 3" in [
            caption.value for caption in at.caption
        ]
        assert len(at.dataframe[0].value) == 3
        assert len(at.dataframe[1].value) == 3
        assert at.dataframe[1].value["Total_Amount"].sum() == pytest.approx(249.49)
