<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>portico</AssemblyName>
    <RootNamespace>Portico.App</RootNamespace>
    <OutputType>Exe</OutputType>
    <RequiresRociSource>true</RequiresRociSource>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Portico.Application/Portico.Application.csproj" />
    <ProjectReference Include="../Portico.Cli/Portico.Cli.csproj" />
    <ProjectReference Include="../Portico.Configuration/Portico.Configuration.csproj" />
    <ProjectReference Include="../Portico.Data/Portico.Data.csproj" />
    <ProjectReference Include="../Portico.Desktop/Portico.Desktop.csproj" />
  </ItemGroup>
</Project>
