<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Portico.Adapters</AssemblyName>
    <RootNamespace>Portico.Adapters</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Portico.Dashboard/Portico.Dashboard.csproj" />
    <ProjectReference Include="../Portico.Finance/Portico.Finance.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" />
  </ItemGroup>
</Project>
