<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Portico.Desktop</AssemblyName>
    <RootNamespace>Portico.Desktop</RootNamespace>
    <RequiresRociSource>true</RequiresRociSource>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Portico.Application/Portico.Application.csproj" />
    <ProjectReference Include="$(RociSourceRoot)/src/Roci.Core/Roci.Core.csproj" />
  </ItemGroup>
</Project>
