<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RequiresRociSource>true</RequiresRociSource>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Portico.App/Portico.App.csproj" />
    <ProjectReference Include="../../src/Portico.Finance/Portico.Finance.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
